# Generated by Django 4.1.3 on 2022-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_encoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPackagerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rawvideo',
            name='video_file',
            field=models.FileField(upload_to='raw/<function createVideoDir at 0x0000020834B140D0>'),
        ),
    ]
