# Generated by Django 4.1.3 on 2022-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_encoder', '0002_videopackagersettings_alter_rawvideo_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawvideo',
            name='video_file',
            field=models.FileField(upload_to='raw/'),
        ),
    ]
