# Generated by Django 4.1.3 on 2022-11-13 13:31

from django.db import migrations, models
import django.db.models.deletion
import video_encoder.utility


class Migration(migrations.Migration):

    dependencies = [
        ('video_encoder', '0003_alter_rawvideo_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='VideoPackagerSettings',
            new_name='VideoEncodingSettings',
        ),
        migrations.AddField(
            model_name='rawvideo',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawvideo',
            name='video_file',
            field=models.FileField(upload_to=video_encoder.utility.generateRawVidDir),
        ),
        migrations.CreateModel(
            name='StreamingVideoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video_encoder.rawvideo')),
            ],
        ),
    ]
