# Generated by Django 4.1.3 on 2022-11-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_encoder', '0004_inputsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideo',
            name='thumbail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
