# Generated by Django 4.1.3 on 2022-11-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_encoder', '0005_rawvideo_thumbail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawvideo',
            old_name='thumbail',
            new_name='thumbnail',
        ),
    ]
