# Generated by Django 4.1.3 on 2022-11-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_encoder', '0006_rename_thumbail_rawvideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawvideo',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rawvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
