# Generated by Django 4.1.3 on 2022-11-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_encoder', '0008_rawvideo_hls_link_rawvideo_is_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamingVideoDetails',
            new_name='PublishedVideos',
        ),
        migrations.DeleteModel(
            name='InputSettings',
        ),
        migrations.DeleteModel(
            name='VideoEncodingSettings',
        ),
    ]
